# Site settings
title: Muj hudebni webik
email:
description: > # this means to ignore newlines until "baseurl:"
  Můj, zatím nedokončený, hudební webík.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jada.tk" # the base hostname & protocol for your site
owner:
  name: Radek Jančík
twitter_username: jekyllrb
github_username:  jada6

permalink: /:categories/:title

paginate: 4
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
encoding: utf-8
gems:
   - octopress-filters
