# Site settings
title: Muj hudebni webik
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jada6

permalink: /:categories/:title

paginate: 4
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
encoding: utf-8
gems:
   - octopress-filters